### ISSUE TITLE
GET /v1/orders method to show orders for users without personal data

### ISSUE THREAD

**Issue by ZharIvan** [CSR-LC/csr-be#105]
User should be able to see their orders in the user profile. The personal data confirmation should not affect this function.

The method GET /v1/orders should be available for both states: 
State1
"slug": "user",
"isRegistrationConfirmed": true,
"isPersonalDataConfirmed": true,
"isReadonly": false

State2
"slug": "user",
"isRegistrationConfirmed": true,
"isPersonalDataConfirmed": false,
"isReadonly": false

**Comment by wvxiw8** [comment]
And I sorted all endpoints alphabetically in the config
